// Auto-generated by scripts/fetch-github-data.mjs
// Do not edit manually - run "npm run fetch-data" to regenerate

export interface GitHubProfile {
  login: string;
  name: string;
  bio: string;
  avatarUrl: string;
  htmlUrl: string;
  publicRepos: number;
  followers: number;
  following: number;
  createdAt: string;
}

export interface GitHubRepo {
  id: number;
  name: string;
  fullName: string;
  description: string | null;
  htmlUrl: string;
  homepage: string | null;
  language: string | null;
  stargazersCount: number;
  forksCount: number;
  openIssuesCount: number;
  topics: string[];
  pushedAt: string;
  createdAt: string;
  license: string | null;
}

export interface GitHubEvent {
  type: string;
  repo: string;
  createdAt: string;
  payload: Record<string, any>;
}

export const githubProfile: GitHubProfile = {
  "login": "lxcxjxhx",
  "name": "Hyacinth-of-Security",
  "bio": "安全风信子 AI x 信息安全实践者",
  "avatarUrl": "https://avatars.githubusercontent.com/u/144213008?v=4",
  "htmlUrl": "https://github.com/lxcxjxhx",
  "publicRepos": 25,
  "followers": 37,
  "following": 25,
  "createdAt": "2023-09-06T07:19:49Z"
};

export const githubRepos: GitHubRepo[] = [
  {
    "id": 1305764793,
    "name": "academic-resume",
    "fullName": "lxcxjxhx/academic-resume",
    "description": "Academic resume for research assistant applications (auto PDF/DOCX)",
    "htmlUrl": "https://github.com/lxcxjxhx/academic-resume",
    "homepage": null,
    "language": "HTML",
    "stargazersCount": 1,
    "forksCount": 0,
    "openIssuesCount": 0,
    "topics": [],
    "pushedAt": "2026-07-19T14:16:19Z",
    "createdAt": "2026-07-19T14:15:55Z",
    "license": null
  },
  {
    "id": 1139856034,
    "name": "HOS_SKILL_WORKFLOW",
    "fullName": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "description": "HOS工作流提示词工厂",
    "htmlUrl": "https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW",
    "homepage": null,
    "language": "TypeScript",
    "stargazersCount": 2,
    "forksCount": 0,
    "openIssuesCount": 0,
    "topics": [],
    "pushedAt": "2026-07-21T11:12:28Z",
    "createdAt": "2026-01-22T14:04:19Z",
    "license": "MIT"
  },
  {
    "id": 1302675500,
    "name": "HOS-Model-Optimizer",
    "fullName": "lxcxjxhx/HOS-Model-Optimizer",
    "description": "HOS 小模型优化工具 - 集成 llama.cpp/vLLM/SGLang 的量化、推理、训练、部署一站式解决方案",
    "htmlUrl": "https://github.com/lxcxjxhx/HOS-Model-Optimizer",
    "homepage": null,
    "language": "Python",
    "stargazersCount": 3,
    "forksCount": 0,
    "openIssuesCount": 0,
    "topics": [],
    "pushedAt": "2026-07-21T08:13:43Z",
    "createdAt": "2026-07-16T11:02:27Z",
    "license": "MIT"
  },
  {
    "id": 1199326655,
    "name": "HOS-LS",
    "fullName": "lxcxjxhx/HOS-LS",
    "description": "HOS-LS 是一个以 AI 为核心的代码安全分析与攻击链推理系统，从规则驱动转变为 AI 驱动，包含 AI 语义分析引擎、攻击链分析引擎、多Agent架构、Exploit生成和自动验证等核心功能。",
    "htmlUrl": "https://github.com/lxcxjxhx/HOS-LS",
    "homepage": null,
    "language": "Python",
    "stargazersCount": 3,
    "forksCount": 1,
    "openIssuesCount": 4,
    "topics": [],
    "pushedAt": "2026-07-21T04:37:09Z",
    "createdAt": "2026-04-02T08:41:20Z",
    "license": "MIT"
  },
  {
    "id": 1305056996,
    "name": "HOS-Forge",
    "fullName": "lxcxjxhx/HOS-Forge",
    "description": "HOS-Forge: AI Native Cyber Security IDE based on OpenHands — 基于 OpenHands 二次开发的 AI 原生网络安全 IDE",
    "htmlUrl": "https://github.com/lxcxjxhx/HOS-Forge",
    "homepage": null,
    "language": "Python",
    "stargazersCount": 5,
    "forksCount": 0,
    "openIssuesCount": 12,
    "topics": [],
    "pushedAt": "2026-07-20T08:11:44Z",
    "createdAt": "2026-07-18T16:27:18Z",
    "license": "NOASSERTION"
  },
  {
    "id": 980504857,
    "name": "HOS-Qian-jia-hong-resume",
    "fullName": "lxcxjxhx/HOS-Qian-jia-hong-resume",
    "description": "RES-PJEXP is a structured digital portfolio showcasing the technical achievements, certifications, and project work of  Qian Jiahong, with a focus on Cybersecurity, Artificial Intelligence, and Healthcare Technology.",
    "htmlUrl": "https://github.com/lxcxjxhx/HOS-Qian-jia-hong-resume",
    "homepage": "",
    "language": "HTML",
    "stargazersCount": 2,
    "forksCount": 0,
    "openIssuesCount": 0,
    "topics": [],
    "pushedAt": "2026-07-21T02:23:57Z",
    "createdAt": "2025-05-09T08:36:26Z",
    "license": null
  },
  {
    "id": 987559727,
    "name": "HOS-MATCH-PROJECT",
    "fullName": "lxcxjxhx/HOS-MATCH-PROJECT",
    "description": "由五位参加intel人工智能大赛的成员完成的AI+信息安全项目",
    "htmlUrl": "https://github.com/lxcxjxhx/HOS-MATCH-PROJECT",
    "homepage": "",
    "language": "Python",
    "stargazersCount": 2,
    "forksCount": 0,
    "openIssuesCount": 0,
    "topics": [],
    "pushedAt": "2026-07-16T12:37:27Z",
    "createdAt": "2025-05-21T08:52:48Z",
    "license": "NOASSERTION"
  },
  {
    "id": 1217940903,
    "name": "BOS-NI",
    "fullName": "lxcxjxhx/BOS-NI",
    "description": "BOS-NI",
    "htmlUrl": "https://github.com/lxcxjxhx/BOS-NI",
    "homepage": null,
    "language": null,
    "stargazersCount": 1,
    "forksCount": 0,
    "openIssuesCount": 0,
    "topics": [],
    "pushedAt": "2026-07-16T12:31:45Z",
    "createdAt": "2026-04-22T11:24:34Z",
    "license": "MIT"
  },
  {
    "id": 1245204270,
    "name": "BOS-FS",
    "fullName": "lxcxjxhx/BOS-FS",
    "description": "FUCKING SUBMIT",
    "htmlUrl": "https://github.com/lxcxjxhx/BOS-FS",
    "homepage": null,
    "language": "Python",
    "stargazersCount": 1,
    "forksCount": 0,
    "openIssuesCount": 0,
    "topics": [],
    "pushedAt": "2026-07-16T12:31:44Z",
    "createdAt": "2026-05-21T02:27:42Z",
    "license": "MIT"
  }
];

export const githubEvents: GitHubEvent[] = [
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-21T14:49:46Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "huggingface/transformers",
    "createdAt": "2026-07-21T14:36:48Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 47456,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/transformers",
    "createdAt": "2026-07-21T14:36:21Z",
    "payload": {
      "action": null,
      "ref": "fix/tokenizers-version-bound",
      "ref_type": "branch"
    }
  },
  {
    "type": "IssueCommentEvent",
    "repo": "huggingface/transformers",
    "createdAt": "2026-07-21T14:25:05Z",
    "payload": {
      "action": "created",
      "ref": null,
      "ref_type": null,
      "issues": {
        "number": 47446,
        "title": "fix: correct typos in comments",
        "html_url": "https://github.com/huggingface/transformers/pull/47446"
      },
      "comment": {
        "body": "> We're trying not to do these small typo fixes right now! We'll do an agent pass or something to fix them all at once at some point\r\n\r\nthanks\r\n"
      }
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-21T13:56:32Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-21T12:56:37Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T11:12:28Z",
    "payload": {
      "action": "merged",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T11:12:29Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T11:12:21Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T10:47:43Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/feature/hos-ip-writing",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T09:29:24Z",
    "payload": {
      "action": "merged",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 1,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T09:29:25Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "IssueCommentEvent",
    "repo": "microsoft/PyRIT",
    "createdAt": "2026-07-21T09:27:10Z",
    "payload": {
      "action": "created",
      "ref": null,
      "ref_type": null,
      "issues": {
        "number": 2233,
        "title": "feat: expand SupportedContentType enum with common media types",
        "html_url": "https://github.com/microsoft/PyRIT/pull/2233"
      },
      "comment": {
        "body": "I've addressed all the review feedback:\n\n1. **Deterministic content type mapping**: Replaced \\mimetypes.guess_type\\ with a fixed extension-to-\\SupportedContentType\\ mapping to avoid platform-dependent behavior. All advertised extensions now map consistently.\n\n2. **Text-only validation for AzureBlobStorageTarget**: Added validation to restrict \\\blob_content_type\\ to text-based types only (PLAIN_TEXT, HTML, JSON, XML, CSV, MARKDOWN). Binary types like PNG, PDF, audio, and video are now rejected with a clear error message.\n\n3. **Audio serializer WAV/MP3 mismatch**: Fixed \\save_formatted_audio_async\\ to force \\.wav\\ extension and explicitly use \\\u0007udio/wav\\ content type, since the method always writes RIFF/WAVE format.\n\n4. **Backward compatibility**: Maintained the \\content_type: str | None = None\\ parameter signature in \\StorageIO.write_file_async\\ to preserve compatibility with existing implementations.\n\n@romanlutz could you please re-review when you have a chance?"
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/PyRIT",
    "createdAt": "2026-07-21T09:26:47Z",
    "payload": {
      "action": null,
      "ref": "pr-2233",
      "ref_type": "branch"
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T09:22:16Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 1,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T09:21:57Z",
    "payload": {
      "action": null,
      "ref": "feature/hos-ip-writing",
      "ref_type": "branch"
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T09:21:42Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS_SKILL_WORKFLOW",
    "createdAt": "2026-07-21T09:06:37Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/axolotl",
    "createdAt": "2026-07-21T09:03:42Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/refactor/use-ignore-index-constant",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "langgenius/dify",
    "createdAt": "2026-07-21T08:15:28Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 39357,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/dify",
    "createdAt": "2026-07-21T08:14:47Z",
    "payload": {
      "action": null,
      "ref": "fix/issue-37468-replace-mock-log-with-caplog",
      "ref_type": "branch"
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS-Model-Optimizer",
    "createdAt": "2026-07-21T08:13:44Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/master",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "axolotl-ai-cloud/axolotl",
    "createdAt": "2026-07-21T08:12:20Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 3862,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/axolotl",
    "createdAt": "2026-07-21T08:11:45Z",
    "payload": {
      "action": null,
      "ref": "refactor/use-ignore-index-constant",
      "ref_type": "branch"
    }
  },
  {
    "type": "ForkEvent",
    "repo": "axolotl-ai-cloud/axolotl",
    "createdAt": "2026-07-21T08:11:31Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "ForkEvent",
    "repo": "langgenius/dify",
    "createdAt": "2026-07-21T08:06:46Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "huggingface/accelerate",
    "createdAt": "2026-07-21T07:44:30Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 4132,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/accelerate",
    "createdAt": "2026-07-21T07:43:11Z",
    "payload": {
      "action": null,
      "ref": "refactor/extract-device-memory-detection",
      "ref_type": "branch"
    }
  },
  {
    "type": "ForkEvent",
    "repo": "huggingface/accelerate",
    "createdAt": "2026-07-21T07:42:59Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "NVIDIA/Megatron-LM",
    "createdAt": "2026-07-21T07:34:47Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 5919,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/Megatron-LM",
    "createdAt": "2026-07-21T07:33:37Z",
    "payload": {
      "action": null,
      "ref": "fix/replace-assert-with-exceptions",
      "ref_type": "branch"
    }
  },
  {
    "type": "ForkEvent",
    "repo": "NVIDIA/Megatron-LM",
    "createdAt": "2026-07-21T07:33:23Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/vllm",
    "createdAt": "2026-07-21T05:18:31Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/test/parse-id-list-unit-tests",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "lxcxjxhx/HOS-Model-Optimizer",
    "createdAt": "2026-07-21T04:40:40Z",
    "payload": {
      "action": "merged",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 1,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS-Model-Optimizer",
    "createdAt": "2026-07-21T04:40:41Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/master",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS-LS",
    "createdAt": "2026-07-21T04:37:10Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "huggingface/transformers",
    "createdAt": "2026-07-21T04:32:47Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 47446,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/transformers",
    "createdAt": "2026-07-21T04:32:36Z",
    "payload": {
      "action": null,
      "ref": "fix/typo-corrections",
      "ref_type": "branch"
    }
  },
  {
    "type": "ForkEvent",
    "repo": "huggingface/transformers",
    "createdAt": "2026-07-21T04:30:35Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "sgl-project/sglang",
    "createdAt": "2026-07-21T04:27:39Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 31886,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "huggingface/datasets",
    "createdAt": "2026-07-21T04:27:31Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 8347,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/datasets",
    "createdAt": "2026-07-21T04:27:19Z",
    "payload": {
      "action": null,
      "ref": "fix/typos-and-raise-patterns",
      "ref_type": "branch"
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "vllm-project/vllm",
    "createdAt": "2026-07-21T04:27:18Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 49280,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "ForkEvent",
    "repo": "huggingface/datasets",
    "createdAt": "2026-07-21T04:27:08Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/sglang",
    "createdAt": "2026-07-21T04:27:04Z",
    "payload": {
      "action": null,
      "ref": "fix/llama32-bare-except",
      "ref_type": "branch"
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/vllm",
    "createdAt": "2026-07-21T04:27:01Z",
    "payload": {
      "action": null,
      "ref": "test/parse-id-list-unit-tests",
      "ref_type": "branch"
    }
  },
  {
    "type": "ForkEvent",
    "repo": "vllm-project/vllm",
    "createdAt": "2026-07-21T04:26:50Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "huggingface/peft",
    "createdAt": "2026-07-21T04:26:50Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 3462,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/peft",
    "createdAt": "2026-07-21T04:26:35Z",
    "payload": {
      "action": null,
      "ref": "fix/bare-except-clauses",
      "ref_type": "branch"
    }
  },
  {
    "type": "ForkEvent",
    "repo": "sgl-project/sglang",
    "createdAt": "2026-07-21T04:26:33Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "ForkEvent",
    "repo": "huggingface/peft",
    "createdAt": "2026-07-21T04:26:24Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS-Model-Optimizer",
    "createdAt": "2026-07-21T04:16:44Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/fix/optimization-round-1",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/HOS-Model-Optimizer",
    "createdAt": "2026-07-21T04:08:19Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/fix/optimization-round-1",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "lxcxjxhx/HOS-Model-Optimizer",
    "createdAt": "2026-07-21T03:53:08Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 1,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/HOS-Model-Optimizer",
    "createdAt": "2026-07-21T03:52:45Z",
    "payload": {
      "action": null,
      "ref": "fix/optimization-round-1",
      "ref_type": "branch"
    }
  },
  {
    "type": "WatchEvent",
    "repo": "QianEric/qianeric.github.io",
    "createdAt": "2026-07-21T03:20:17Z",
    "payload": {
      "action": "started",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "WatchEvent",
    "repo": "QianEric/404app",
    "createdAt": "2026-07-21T03:20:06Z",
    "payload": {
      "action": "started",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "IssueCommentEvent",
    "repo": "microsoft/PyRIT",
    "createdAt": "2026-07-21T02:33:15Z",
    "payload": {
      "action": "created",
      "ref": null,
      "ref_type": null,
      "issues": {
        "number": 2233,
        "title": "feat: expand SupportedContentType enum with common media types",
        "html_url": "https://github.com/microsoft/PyRIT/pull/2233"
      },
      "comment": {
        "body": "I have addressed all the review feedback:\n\n1. **MIME type integration**: Added `content_type` parameter to `write_file_async` with auto-inference from file extension via `mimetypes.guess_type`, falling back to configured default\n2. **Serializer propagation**: `save_data_async`, `save_b64_image_async`, `save_formatted_audio_async` now pass inferred content_type to storage layer\n3. **Enum consolidation**: Removed duplicate `SupportedContentType` from `azure_blob_storage_target.py`, unified all imports to `pyrit.memory.storage.storage`\n\n@romanlutz could you please re-review when you have a chance?"
      }
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/PyRIT",
    "createdAt": "2026-07-21T02:32:59Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/feat/expand-supported-content-types",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/PyRIT",
    "createdAt": "2026-07-20T15:19:47Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/feat/expand-supported-content-types",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "MoonNightSkytoyou/excel-masking-tool",
    "createdAt": "2026-07-20T15:12:12Z",
    "payload": {
      "action": "merged",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "MoonNightSkytoyou/excel-masking-tool",
    "createdAt": "2026-07-20T14:57:48Z",
    "payload": {
      "action": "merged",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 1,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "MoonNightSkytoyou/excel-masking-tool",
    "createdAt": "2026-07-20T14:51:39Z",
    "payload": {
      "action": "merged",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 3,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "MoonNightSkytoyou/excel-masking-tool",
    "createdAt": "2026-07-20T14:15:07Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 3,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "MoonNightSkytoyou/excel-masking-tool",
    "createdAt": "2026-07-20T14:14:54Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "MoonNightSkytoyou/excel-masking-tool",
    "createdAt": "2026-07-20T14:14:44Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 1,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx",
    "createdAt": "2026-07-20T08:05:19Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-20T07:53:30Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx",
    "createdAt": "2026-07-20T07:40:28Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-20T07:24:34Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-20T07:12:34Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx",
    "createdAt": "2026-07-20T07:06:08Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx",
    "createdAt": "2026-07-20T06:59:23Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx",
    "createdAt": "2026-07-20T06:52:37Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-20T06:37:16Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx",
    "createdAt": "2026-07-20T06:33:53Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx",
    "createdAt": "2026-07-20T06:30:52Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "morningD/page-counter",
    "createdAt": "2026-07-20T06:08:30Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 1,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "morningD/license.atlas",
    "createdAt": "2026-07-20T06:08:28Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "morningD/ECNU-literature-quick-access",
    "createdAt": "2026-07-20T06:08:26Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 4,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/page-counter",
    "createdAt": "2026-07-20T06:07:53Z",
    "payload": {
      "action": null,
      "ref": "fix/enforce-body-size-limit",
      "ref_type": "branch"
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/license.atlas",
    "createdAt": "2026-07-20T06:07:52Z",
    "payload": {
      "action": null,
      "ref": "fix/standard-tailwind-opacity",
      "ref_type": "branch"
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/ECNU-literature-quick-access",
    "createdAt": "2026-07-20T06:07:49Z",
    "payload": {
      "action": null,
      "ref": "fix/remove-problematic-domains",
      "ref_type": "branch"
    }
  },
  {
    "type": "ForkEvent",
    "repo": "morningD/page-counter",
    "createdAt": "2026-07-20T06:07:27Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "ForkEvent",
    "repo": "morningD/license.atlas",
    "createdAt": "2026-07-20T06:07:26Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "ForkEvent",
    "repo": "morningD/ECNU-literature-quick-access",
    "createdAt": "2026-07-20T06:07:25Z",
    "payload": {
      "action": "forked",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "WatchEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-20T05:00:39Z",
    "payload": {
      "action": "started",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-20T04:59:22Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/main",
      "ref_type": null
    }
  },
  {
    "type": "IssueCommentEvent",
    "repo": "microsoft/PyRIT",
    "createdAt": "2026-07-20T04:23:21Z",
    "payload": {
      "action": "created",
      "ref": null,
      "ref_type": null,
      "issues": {
        "number": 2233,
        "title": "feat: expand SupportedContentType enum with common media types",
        "html_url": "https://github.com/microsoft/PyRIT/pull/2233"
      },
      "comment": {
        "body": "@microsoft-github-policy-service agree"
      }
    }
  },
  {
    "type": "IssueCommentEvent",
    "repo": "microsoft/PyRIT",
    "createdAt": "2026-07-20T04:21:30Z",
    "payload": {
      "action": "created",
      "ref": null,
      "ref_type": null,
      "issues": {
        "number": 2233,
        "title": "feat: expand SupportedContentType enum with common media types",
        "html_url": "https://github.com/microsoft/PyRIT/pull/2233"
      },
      "comment": {
        "body": "感谢 @romanlutz 的详细反馈！我已经按照您的建议进行了修改：\n\n1. **修改了 `AzureBlobStorageIO.write_file_async` 方法**：新增了可选的 `content_type` 参数，允许为每个文件指定 MIME 类型。\n\n2. **实现了 MIME 类型自动推断逻辑**：使用 `mimetypes.guess_type` 根据文件扩展名自动推断内容类型（当未明确提供时）。\n\n3. **更新了序列化器**：修改了 `save_data_async`、`save_b64_image_async` 和 `save_formatted_audio_async`，在保存数据时传递推断的 `content_type`。\n\n4. **整合了重复的枚举**：移除了重复的 `AzureBlobStorageTarget` 枚举，统一从 `pyrit.memory.storage.storage` 导入 `SupportedContentType`。\n\n5. **添加了单元测试**：创建了测试用例来验证 content_type 的推断和传递逻辑。\n\n6. **测试说明**：由于本地环境限制（Windows 缺少完整依赖），依赖 CI/CD 自动运行完整测试套件。\n\n这些修改应该能够正确支持广告中声明的媒体类型，通过将 MIME 选择逻辑集成到文件上传工作流中。如果需要进一步修改，请告诉我！"
      }
    }
  },
  {
    "type": "PullRequestReviewCommentEvent",
    "repo": "microsoft/PyRIT",
    "createdAt": "2026-07-20T04:21:07Z",
    "payload": {
      "action": "created",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2233,
        "title": "",
        "html_url": ""
      },
      "comment": {
        "body": "Thank you for the detailed feedback, @romanlutz! I've addressed your concerns:\n\n1. **Modified `AzureBlobStorageIO.write_file_async`**: Added an optional `content_type` parameter that allows specifying the MIME type per file.\n\n2. **Auto-detection of MIME types**: Implemented logic using `mimetypes.guess_type` to automatically infer the content type from file extensions when not explicitly provided.\n\n3. **Updated serializers**: Modified `save_data_async`, `save_b64_image_async`, and `save_formatted_audio_async` to pass the inferred `content_type` when saving data.\n\n4. **Consolidated `SupportedContentType` enum**: Removed the duplicate `AzureBlobStorageTarget` enum and unified the content type definitions in `pyrit.memory.storage.storage`.\n\n5. **Added unit tests**: Created tests to verify the content type inference and propagation logic.\n\n6. **Testing**: Due to local environment constraints (incomplete dependencies on Windows), I'm relying on the CI/CD pipeline to run the full test suite automatically.\n\nThe changes should now properly enable the advertised media types by wiring MIME selection into the file upload workflow. Please let me know if you need any additional modifications!"
      }
    }
  },
  {
    "type": "PullRequestReviewEvent",
    "repo": "microsoft/PyRIT",
    "createdAt": "2026-07-20T04:21:07Z",
    "payload": {
      "action": "created",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2233,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "PushEvent",
    "repo": "lxcxjxhx/PyRIT",
    "createdAt": "2026-07-20T04:19:00Z",
    "payload": {
      "action": null,
      "ref": "refs/heads/feat/expand-supported-content-types",
      "ref_type": null
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "intel/neural-compressor",
    "createdAt": "2026-07-20T02:38:53Z",
    "payload": {
      "action": "merged",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2526,
        "title": "",
        "html_url": ""
      }
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/lxcxjxhx.github.io",
    "createdAt": "2026-07-20T02:30:07Z",
    "payload": {
      "action": null,
      "ref": "main",
      "ref_type": "branch"
    }
  },
  {
    "type": "WatchEvent",
    "repo": "MoonNightSkytoyou/excel-masking-tool",
    "createdAt": "2026-07-20T01:20:17Z",
    "payload": {
      "action": "started",
      "ref": null,
      "ref_type": null
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/academic-resume",
    "createdAt": "2026-07-19T14:16:19Z",
    "payload": {
      "action": null,
      "ref": "main",
      "ref_type": "branch"
    }
  },
  {
    "type": "CreateEvent",
    "repo": "lxcxjxhx/academic-resume",
    "createdAt": "2026-07-19T14:16:04Z",
    "payload": {
      "action": null,
      "ref": "master",
      "ref_type": "branch"
    }
  },
  {
    "type": "PullRequestEvent",
    "repo": "microsoft/PyRIT",
    "createdAt": "2026-07-19T13:23:21Z",
    "payload": {
      "action": "opened",
      "ref": null,
      "ref_type": null,
      "pulls": {
        "number": 2233,
        "title": "",
        "html_url": ""
      }
    }
  }
];
