// Auto-generated by scripts/fetch-resume-data.mjs — do not edit.
// Source: https://github.com/lxcxjxhx/HOS-Qian-jia-hong-resume (PR/README.md) @ 2026-08-20T23:40:06.925Z
export const source = {"file":"PR/README.md","fetchedAt":"2026-08-20T23:40:06.925Z"};
export const markdown = `# Open Source PR Records

Merged Pull Requests across open source projects.

## Summary

- **Total Merged PRs**: 100
- **Projects**: 19

## PR List

| Repository | PR | Title | Merged |
|------------|-----|-------|--------|
| [Bearer/bearer](https://github.com/Bearer/bearer) | [#2007](https://github.com/Bearer/bearer/pull/2007) | fix: use %w for error wrapping in scan command | 2026-07-29 |
| [DefectDojo/django-DefectDojo](https://github.com/DefectDojo/django-DefectDojo) | [#15430](https://github.com/DefectDojo/django-DefectDojo/pull/15430) | fix: replace bare except with specific exception types | 2026-07-30 |
| [DefectDojo/django-DefectDojo](https://github.com/DefectDojo/django-DefectDojo) | [#15391](https://github.com/DefectDojo/django-DefectDojo/pull/15391) | fix: add missing return after exception in GitHub issue handlers | 2026-07-29 |
| [GH05TCREW/pentestagent](https://github.com/GH05TCREW/pentestagent) | [#86](https://github.com/GH05TCREW/pentestagent/pull/86) | fix: use context manager for tarfile operations in DockerRuntime | 2026-07-30 |
| [aquasecurity/trivy](https://github.com/aquasecurity/trivy) | [#11013](https://github.com/aquasecurity/trivy/pull/11013) | refactor(alpine): remove type assertion when reading the APKINDEX archive | 2026-07-30 |
| [bytedance/g3](https://github.com/bytedance/g3) | [#1103](https://github.com/bytedance/g3/pull/1103) | fix(g3-types): replace unsafe unwrap() with proper error handling in openssl cert pair | 2026-07-31 |
| [lxcxjxhx/BOS-FS](https://github.com/lxcxjxhx/BOS-FS) | [#1](https://github.com/lxcxjxhx/BOS-FS/pull/1) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/BOS-NI](https://github.com/lxcxjxhx/BOS-NI) | [#2](https://github.com/lxcxjxhx/BOS-NI/pull/2) | chore: 清理残留的旧 MIT 许可证文件与 README 引用 | 2026-08-02 |
| [lxcxjxhx/BOS-NI](https://github.com/lxcxjxhx/BOS-NI) | [#1](https://github.com/lxcxjxhx/BOS-NI/pull/1) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#11](https://github.com/lxcxjxhx/HOS-ARES/pull/11) | feat: rootfs build infrastructure - Docker + Windows/Linux scripts | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#10](https://github.com/lxcxjxhx/HOS-ARES/pull/10) | feat: UI progress cards + Settings connectivity test + SkillRegistry | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#9](https://github.com/lxcxjxhx/HOS-ARES/pull/9) | feat: TerminalActivity UI fix + MainActivity integration | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#8](https://github.com/lxcxjxhx/HOS-ARES/pull/8) | feat: bootstrap.sh pre-installed validation + entry.sh tool shims | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#7](https://github.com/lxcxjxhx/HOS-ARES/pull/7) | feat: ProotRuntime pre-installed mode + incremental update + error humanization | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#6](https://github.com/lxcxjxhx/HOS-ARES/pull/6) | feat: reasonix agent parallel scheduling + soft routing | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#5](https://github.com/lxcxjxhx/HOS-ARES/pull/5) | refactor: remove Strix UI layer + securityresearch agent (~37K lines) | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#4](https://github.com/lxcxjxhx/HOS-ARES/pull/4) | refactor: remove pentestgpt agent (~5.5K lines) | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#3](https://github.com/lxcxjxhx/HOS-ARES/pull/3) | refactor: remove deepaudit agent (~40K lines) | 2026-08-17 |
| [lxcxjxhx/HOS-ARES](https://github.com/lxcxjxhx/HOS-ARES) | [#2](https://github.com/lxcxjxhx/HOS-ARES/pull/2) | build: optimize APK size + upgrade build toolchain | 2026-08-17 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#46](https://github.com/lxcxjxhx/HOS-Forge/pull/46) | chore: 清理残留的旧 MIT 许可证文件与 README 引用 | 2026-08-02 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#45](https://github.com/lxcxjxhx/HOS-Forge/pull/45) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#44](https://github.com/lxcxjxhx/HOS-Forge/pull/44) | feat: add version locking, pipeline error strategies, and registry-pipeline integration | 2026-07-30 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#43](https://github.com/lxcxjxhx/HOS-Forge/pull/43) | feat: implement real marketplace backend, skill init toolchain, sandbox execution, and performance optimization | 2026-07-29 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#42](https://github.com/lxcxjxhx/HOS-Forge/pull/42) | test: add security isolation tests for skill execution | 2026-07-29 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#41](https://github.com/lxcxjxhx/HOS-Forge/pull/41) | test: add integration tests for IDE adapters and CLI | 2026-07-29 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#40](https://github.com/lxcxjxhx/HOS-Forge/pull/40) | docs: enhance documentation with API reference and guides | 2026-07-28 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#39](https://github.com/lxcxjxhx/HOS-Forge/pull/39) | test: add integration tests for skill system and MCP server | 2026-07-28 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#38](https://github.com/lxcxjxhx/HOS-Forge/pull/38) | refactor: restructure to IDE-agnostic skill+plugin architecture | 2026-07-28 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#34](https://github.com/lxcxjxhx/HOS-Forge/pull/34) | feat(mcp-server): add error handling and startup verification | 2026-07-27 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#33](https://github.com/lxcxjxhx/HOS-Forge/pull/33) | feat(taskflow): implement executable taskflow engine with parallel execution | 2026-07-27 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#31](https://github.com/lxcxjxhx/HOS-Forge/pull/31) | feat(cli): fix entry point configuration and add CLI tests | 2026-07-27 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#36](https://github.com/lxcxjxhx/HOS-Forge/pull/36) | feat: implement TrivyTool and enhance security tools integration | 2026-07-27 |
| [lxcxjxhx/HOS-Forge](https://github.com/lxcxjxhx/HOS-Forge) | [#35](https://github.com/lxcxjxhx/HOS-Forge/pull/35) | feat: enhance Taskflow Engine with parallel execution support | 2026-07-27 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#34](https://github.com/lxcxjxhx/HOS-LS/pull/34) | feat(OPT): 三级 SAST→AI cascade 流水线 + 省钱策略 + 去重归属 | 2026-08-16 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#33](https://github.com/lxcxjxhx/HOS-LS/pull/33) | chore: gitignore 忽略 CodeGraph 预索引目录 | 2026-08-15 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#32](https://github.com/lxcxjxhx/HOS-LS/pull/32) | feat: M6 文件级并发可配置 + 缓存命中统计上报 | 2026-08-15 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#31](https://github.com/lxcxjxhx/HOS-LS/pull/31) | feat: M7 CWE 专项检测指引接线（配置门默认关） | 2026-08-15 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#30](https://github.com/lxcxjxhx/HOS-LS/pull/30) | feat: 客户端超时修复 + AST 确定性证据能力（默认关，A/B 验证后收敛） | 2026-08-15 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#29](https://github.com/lxcxjxhx/HOS-LS/pull/29) | feat: 评测分数卡 + JSON 结构化输出 + 响应缓存 + 请求超时 + 提示词优化（M1-M3） | 2026-08-14 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#28](https://github.com/lxcxjxhx/HOS-LS/pull/28) | feat: Agent-6 先分析后判定 + 双轨输出（提升检出） | 2026-08-14 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#27](https://github.com/lxcxjxhx/HOS-LS/pull/27) | fix: Agent-2 风险枚举放宽为候选风险（验证层过滤） | 2026-08-14 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#26](https://github.com/lxcxjxhx/HOS-LS/pull/26) | fix: Agent-6 因 location 绝对路径规则过度 REJECTED 真实漏洞 | 2026-08-14 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#25](https://github.com/lxcxjxhx/HOS-LS/pull/25) | fix: NVD 数据库缺失时降级内置 DB 而非挂起 | 2026-08-14 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#24](https://github.com/lxcxjxhx/HOS-LS/pull/24) | fix: NVD 查询列名 + CWE ETL 导入修复 | 2026-08-13 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#22](https://github.com/lxcxjxhx/HOS-LS/pull/22) | feat: 移除报告中的 APTS 合规披露区块 | 2026-08-13 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#21](https://github.com/lxcxjxhx/HOS-LS/pull/21) | fix: 修复 AI pipeline JSON 输出可靠性问题 | 2026-08-13 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#20](https://github.com/lxcxjxhx/HOS-LS/pull/20) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#19](https://github.com/lxcxjxhx/HOS-LS/pull/19) | fix(cli): correct --dif parameter name to --diff | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#18](https://github.com/lxcxjxhx/HOS-LS/pull/18) | chore(config): update DeepSeek API configuration | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#17](https://github.com/lxcxjxhx/HOS-LS/pull/17) | feat(errors): add APIError exception class for AI providers | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#16](https://github.com/lxcxjxhx/HOS-LS/pull/16) | feat(json_utils): add unified JSON parsing utility module | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#15](https://github.com/lxcxjxhx/HOS-LS/pull/15) | feat(logger): add RotatingFileHandler file output support | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#14](https://github.com/lxcxjxhx/HOS-LS/pull/14) | refactor(result_reviewer): migrate from legacy OpenAI API | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#13](https://github.com/lxcxjxhx/HOS-LS/pull/13) | fix(deepseek): restore actual API test in validate_api_access | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#12](https://github.com/lxcxjxhx/HOS-LS/pull/12) | fix(prompt_evolver): add 5-layer JSON parsing protection | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#11](https://github.com/lxcxjxhx/HOS-LS/pull/11) | fix(pure_ai_analyzer): unify logging and improve error handling | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#10](https://github.com/lxcxjxhx/HOS-LS/pull/10) | fix(multi_agent_pipeline): unify logging and fix hard routing issues | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#9](https://github.com/lxcxjxhx/HOS-LS/pull/9) | refactor(schema_validator): migrate print() to unified logger | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#8](https://github.com/lxcxjxhx/HOS-LS/pull/8) | refactor(file_prioritizer): migrate print() to unified logger | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#7](https://github.com/lxcxjxhx/HOS-LS/pull/7) | refactor(context_builder): migrate print() to unified logger | 2026-07-31 |
| [lxcxjxhx/HOS-LS](https://github.com/lxcxjxhx/HOS-LS) | [#6](https://github.com/lxcxjxhx/HOS-LS/pull/6) | feat: Comprehensive optimization aligned with 8 state-of-the-art SAST papers | 2026-07-31 |
| [lxcxjxhx/HOS-MATCH-PROJECT](https://github.com/lxcxjxhx/HOS-MATCH-PROJECT) | [#1](https://github.com/lxcxjxhx/HOS-MATCH-PROJECT/pull/1) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/HOS-Model-Optimizer](https://github.com/lxcxjxhx/HOS-Model-Optimizer) | [#3](https://github.com/lxcxjxhx/HOS-Model-Optimizer/pull/3) | chore: 清理残留的旧 MIT 许可证文件与 README 引用 | 2026-08-02 |
| [lxcxjxhx/HOS-Model-Optimizer](https://github.com/lxcxjxhx/HOS-Model-Optimizer) | [#2](https://github.com/lxcxjxhx/HOS-Model-Optimizer/pull/2) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/HOS-Qian-jia-hong-resume](https://github.com/lxcxjxhx/HOS-Qian-jia-hong-resume) | [#1](https://github.com/lxcxjxhx/HOS-Qian-jia-hong-resume/pull/1) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#61](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/61) | feat(S-01-HOS-Save-Cost): ponytail-restraint + token-router skills + reasonix.toml template | 2026-08-19 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#60](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/60) | feat: integrate CN-SRC-Hunter bug bounty pipeline methodology | 2026-08-17 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#58](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/58) | feat(S-12): 方法论背书 + CS 审稿 rubric 补全 | 2026-08-11 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#57](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/57) | feat: add X-00 HOS-Chara-Sequence — ComfyUI character portrait sequence generator (entertainment series) | 2026-08-07 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#53](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/53) | feat: 新增 S-13-HOS-Char-Factory 角色素材工厂 skill | 2026-08-06 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#52](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/52) | fix(S-01): 移除不存在的 mcp-compressor 依赖，改为 Reasonix 原生 [[plugins]] MCP 直连 | 2026-08-04 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#51](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/51) | feat(S-01): HOS-Save-Cost 重构为工作流层 Token 管家（四层集成 v2.0） | 2026-08-04 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#50](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/50) | feat(S-12): 新增多篇汇总 HTML 渲染工具 render-summary-html.py | 2026-08-03 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#49](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/49) | fix(S-12): 默认输出升级为 HTML + Evidence 强制联网核验 arXiv/GitHub 元数据 | 2026-08-03 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#48](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/48) | chore: 清理残留的旧 MIT 许可证文件与 README 引用 | 2026-08-02 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#47](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/47) | feat(S-12): 论文输入 tex 源优先 + PDF 多级降级链，输出升级为美观 HTML/PDF | 2026-08-02 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#46](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/46) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#45](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/45) | feat: 新增 S-12-HOS-Critic-Review 六维批判式评审 Skill | 2026-08-02 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#44](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/44) | refactor: W 类编号独立归零（W-12~15 → W-00~03） | 2026-08-02 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#43](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/43) | refactor: 顶层目录增加 S/W 类别前缀区分设计理念 | 2026-08-02 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#42](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/42) | refactor: 统一顶层目录命名与编号顺序管理 | 2026-08-02 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#41](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/41) | feat(contrib): 审核者视角自检门升级 G0–G8 + 合并速度评估维度 | 2026-08-01 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#40](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/40) | refactor: split HOS-GH-ContribOS into a multi-file skill (mirror submit-oss-pr layout) | 2026-08-01 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#39](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/39) | feat: add reviewer-perspective gate, scenario memory, AI disclosure; refactor HOS-GH-ContribOS to multi-file skill | 2026-08-01 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#38](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/38) | feat: 新增 HOS-Paper-RedTeam 论文红队系统（HOS论文鞭尸局） | 2026-07-31 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#37](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/37) | feat: enhance ContribOS with comprehensive experience integration | 2026-07-29 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#36](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/36) | refactor: replace HOS-OSS-Contributor with HOS-GH-ContribOS - unified contribution lifecycle framework | 2026-07-29 |
| [lxcxjxhx/HOS_SKILL_WORKFLOW](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW) | [#35](https://github.com/lxcxjxhx/HOS_SKILL_WORKFLOW/pull/35) | feat: add HOS-OSS-Contributor skill - AI-driven open source contribution workflow | 2026-07-29 |
| [lxcxjxhx/academic-resume](https://github.com/lxcxjxhx/academic-resume) | [#1](https://github.com/lxcxjxhx/academic-resume/pull/1) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/lxcxjxhx](https://github.com/lxcxjxhx/lxcxjxhx) | [#6](https://github.com/lxcxjxhx/lxcxjxhx/pull/6) | chore: 移除 profile 仓库的 LICENSE 文件与展示 | 2026-08-02 |
| [lxcxjxhx/lxcxjxhx](https://github.com/lxcxjxhx/lxcxjxhx) | [#5](https://github.com/lxcxjxhx/lxcxjxhx/pull/5) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [lxcxjxhx/lxcxjxhx.github.io](https://github.com/lxcxjxhx/lxcxjxhx.github.io) | [#1](https://github.com/lxcxjxhx/lxcxjxhx.github.io/pull/1) | chore: 切换许可证为 AGPLv3 并引入 DCO | 2026-08-02 |
| [qianeric-backup/kind-all](https://github.com/qianeric-backup/kind-all) | [#23](https://github.com/qianeric-backup/kind-all/pull/23) | feat: enhance Payment Gate with multi-layer detection and security hardening | 2026-07-27 |
| [qianeric-backup/kind-all](https://github.com/qianeric-backup/kind-all) | [#15](https://github.com/qianeric-backup/kind-all/pull/15) | feat: enhance EventBus with async error handling, timeouts, and priorities | 2026-07-27 |
| [qianeric-backup/kind-all](https://github.com/qianeric-backup/kind-all) | [#13](https://github.com/qianeric-backup/kind-all/pull/13) | refactor: extract state transition rules and add lifecycle hooks | 2026-07-27 |
| [qianeric-backup/kind-all](https://github.com/qianeric-backup/kind-all) | [#11](https://github.com/qianeric-backup/kind-all/pull/11) | feat: add connection pool management and health checks to HTTPAdapter | 2026-07-27 |
| [qianeric-backup/kind-all](https://github.com/qianeric-backup/kind-all) | [#17](https://github.com/qianeric-backup/kind-all/pull/17) | fix: improve scheduler accuracy with monotonic clock and drift compensation | 2026-07-27 |
| [qianeric-backup/kind-all](https://github.com/qianeric-backup/kind-all) | [#19](https://github.com/qianeric-backup/kind-all/pull/19) | feat: add transaction support and concurrency control to SQLite storage | 2026-07-27 |
| [qianeric-backup/kind-all](https://github.com/qianeric-backup/kind-all) | [#21](https://github.com/qianeric-backup/kind-all/pull/21) | perf: optimize AI Vision Solver with caching and batching | 2026-07-27 |
| [zaproxy/zaproxy](https://github.com/zaproxy/zaproxy) | [#9411](https://github.com/zaproxy/zaproxy/pull/9411) | Use try-with-resources in HashUtils | 2026-07-30 |

## Detail Files

Each PR's detailed analysis (code changes, file list, statistics) is auto-generated in subdirectories.

\`\`\`
PR/
├── README.md
├── {repo_name}/
│   ├── PR_{number}.md
│   └── ...
\`\`\`

## Auto Update

Updated daily via GitHub Actions at UTC 00:00.

Last updated: 2026-08-20 01:02:04 UTC

---

**GitHub**: [lxcxjxhx](https://github.com/lxcxjxhx)
`;
